### ISSUE TITLE
Cannot find type 'UUID' in scope in SocketProtocol

### ISSUE THREAD

**Issue by RedDragonJ** [MetaMask/metamask-ios-sdk#177] opened 2024-07-30 20:30 UTC
### Provide environment information

The issue happens when try to build the project which integrated with metamask-ios-sdk. 
This issue does not exist in the SDK version 0.6.5, it started from 0.7.1

### MetaMask iOS SDK Version

0.8.1

### MetaMask Wallet Version

NA

### Xcode Version

Version 15.4 (15F31d)

### iOS Version

17.2

### Describe the Bug

When build the project which integrated with the SDK, it failed to build with this error
![Screenshot 2024-07-30 at 4 27 49 PM](https://github.com/user-attachments/assets/3af5c212-75f9-4071-b930-f924c69f2986)

### Expected Behavior

When build the project which integrated with the SDK should not have any issue, the project build successfully

### Steps To Reproduce

- Integrate SDK 0.7.1+ into a swift project
- Then build the project (or cmd+B)
- The project failed to build with error

**Comment by annemarieshev** [comment] 2024-07-31 02:13
Hello @RedDragonJ 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID MET07638
Please see the link below to our dedicated support line:
[metamask Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by elefantel** [comment] 2024-08-01 08:22
Hi @RedDragonJ thanks for reporting the issue. 

It is caused by not importing `Foundation`. We have fixed it in the linked pull request and will be resolved in the next release version `0.8.2` which will be released in a few hours.

**Comment by RedDragonJ** [comment] 2024-08-01 13:11
Awesome, looking forward to the new update

**Closed** 2024-08-02 11:55 UTC
Labels: planning

**Comment by elefantel** [comment] 2024-08-02 12:24
@RedDragonJ `0.8.2` is not live. Thanks again!
