### ISSUE TITLE
I am getting the mmsdk error message when trying to connect to metamask app from ios app

### ISSUE THREAD

**Issue by nick70007** [MetaMask/metamask-ios-sdk#80] opened 2023-07-20 09:02 UTC
I am getting this error:

mmsdk| Error: Message ["message": BEeJHh8NiNL2FWfHRzBE1jaEQKTxmwmpPbTjDZiVxUWMYO7radxf5i0wA4hxtr5k//PNKpErk+P9uENYiNXCETkknULeBRrXvChoT1njk2FjelDe9gTSj8/oxBO7+scHLh5FmsSAdSgUxD3ZUMuHLis=, "id": BA500B3E-71EF-4116-BE2F-3D4B6FDEBAAA] could not be decoded: The data couldn’t be read because it isn’t in the correct format.
Func: message(from:)
File: Models.swift
Line: 45

How to fix it?

**Comment by nick70007** [comment] 2023-07-20 09:06
and also getting this error when it switches from metamask app to ios app

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidMessage', src/lib.rs:144:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
libc++abi: terminating due to uncaught foreign exception

**Comment by christopherferreira9** [comment] 2023-07-20 09:10
HI @nick70007 ! 
Can you provide the following details:
- MetaMask Wallet version
- iOS SDK version
- Code snippet of the call you're trying to perform

Thank you for reporting!

**Comment by nick70007** [comment] 2023-07-20 09:14
Metamask version: 7.3.0
iOS SDK version: 0.2.0

code snippet
![Screenshot 2023-07-20 at 2 43 56 PM](https://github.com/MetaMask/metamask-ios-sdk/assets/52743988/3a7bbf7d-d312-4e3c-a8c8-432eed52baec)

**Comment by christopherferreira9** [comment] 2023-07-20 10:02
That's awesome, we'll take a look at it as soon as possible. In the meantime, can you try to clear all sessions from MetaMask when the connection loader doesn't show?

**Comment by nick70007** [comment] 2023-07-20 10:05
ok @christopherferreira9 thanks for the response. I will be waiting for your response

**Comment by nick70007** [comment] 2023-07-21 08:24
when it will be fixed @christopherferreira9 ?

**Comment by habasa** [comment] 2023-07-25 01:07
I also faced the same problem. is it fixed??

**Comment by nick70007** [comment] 2023-07-25 01:16
> I also faced the same problem. is it fixed??

No response from the team yet

**Comment by christopherferreira9** [comment] 2023-08-02 09:52
Hi @nick70007 . We are working on trying to replicate this and publish a fix for it.

**Comment by nick70007** [comment] 2023-08-02 09:55
> Hi @nick70007 . We are working on trying to replicate this and publish a fix for it.

sure, thanks for the feedback. When should i expect the next response? @christopherferreira9

**Comment by SunZhiC** [comment] 2023-08-10 08:05
I also meet this error when I try to call addEthereumChain.

mmsdk| Error: Message ["message": BMVs7yHWM2SACvq//4s7CxPxsd04fQ9Ah+FVPY4iFJYO9lh34EgQTGe/xDD5SRzLNUKV9ZfQ/NTFtKbJAdpuvlxduRkYajZ00jC/8+6zXewUq2dPhzaYLvTFTEdqoYaJmeeRDXDb4AQJOrtH5vlGocY=, "id": 8DEDFB0E-9644-425B-98A9-2A730CEA9412] could not be decoded: The data couldn’t be read because it isn’t in the correct format.

MetaMask Wallet version: v7.3.1(1156)
iOS SDK version: 0.2.0
Code snippet of the call you're trying to perform:
```swift
let addChainParams = AddChainRequest(
      chainId: "0x89",
      chainName: "Polygon Mainnet",
      rpcUrls: ["https://polygon-rpc.com/"]
  )
    
  let addChainRequest = EthereumRequest(
      method: .addEthereumChain,
      params: [addChainParams]
  )

  self.ethereum.request(addChainRequest)?.sink(receiveCompletion: { completion in
      switch completion {
      case let .failure(error):
          print(error)
      default: break
      }
  }, receiveValue: { _ in
     print("success")
  }).store(in: &self.cancellables)
                
            
```

**Comment by SunZhiC** [comment] 2023-08-10 08:18
> and also getting this error when it switches from metamask app to ios app
> 
> thread '' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidMessage', src/lib.rs:144:38 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace libc++abi: terminating due to uncaught foreign exception

Sometimes, I meet the same error too, I don't know how to reproduce it, though Firebase caught the crash log, it cant help. I suppose there is some error in your Ecies.xcframework, and can you update it, just throws some swift error, without force crash.
This is a Firebase log, under Stack trace
```
Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x79c4 __pthread_kill + 8
1  libsystem_pthread.dylib        0x7434 pthread_kill + 268
2  libsystem_c.dylib              0x1ff64 abort + 164
3  libc++abi.dylib                0x13bc4 __cxxabiv1::__aligned_malloc_with_fallback(unsigned long) + 130
4  libc++abi.dylib                0x4f10 demangling_terminate_handler() + 132
5  FirebaseCrashlytics            0x18d54 FIRCLSTerminateHandler() + 404
6  libc++abi.dylib                0x12f58 std::__terminate(void (*)()) + 20
7  libc++abi.dylib                0x12ee0 std::terminate() + 44
8  libobjc.A.dylib                0x2a4d4 objc::DenseMapBase<objc::DenseMap<objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >, objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >::FatalCorruptHashTables(objc::detail::DenseMapPair<objc_class*, PendingInitialize*> const*, unsigned int) const + 14
9  libdispatch.dylib              0x3964 _dispatch_client_callout + 40
10 libdispatch.dylib              0x11d30 _dispatch_main_queue_callback_4CF + 940
11 CoreFoundation                 0x51ce4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
12 CoreFoundation                 0xbebc __CFRunLoopRun + 2540
13 CoreFoundation                 0x1f3c8 CFRunLoopRunSpecific + 600
14 GraphicsServices               0x138c GSEventRunModal + 164
15 UIKitCore                      0x51b0bc -[UIApplication _run] + 1100
16 UIKitCore                      0x298be8 UIApplicationMain + 2124
17 libswiftUIKit.dylib            0x31184 UIApplicationMain(_:_:_:_:) + 104
18 Demo                           0x66034 static UIApplicationDelegate.main() + 104 (<compiler-generated>:104)
19 Demo                           0x65fbc static AppDelegate.$main() + 36 (AppDelegate.swift:36)
20 Demo                           0x66aa8 main + 37 (AppDelegate.swift:37)
21 ???                            0x1076a1a24 (Missing)

```

under Keys
```
crash_info_entry_0 | terminating with uncaught foreign exception
crash_info_entry_1 | abort() called
```

**Comment by elefantel** [comment] 2023-08-18 10:18
Hi @nick70007 @habasa , please check out the branch `reconnection-handling` and test and let us know if the issue you experience is fixed?

@SunZhiC that looks a panic from failure to decrypt data, I think it should also be fixed on that same branch, please check and let us know?

**Comment by SunZhiC** [comment] 2023-08-18 12:04
> Hi @nick70007 @habasa , please check out the branch `reconnection-handling` and test and let us know if the issue you experience is fixed?
> 
> @SunZhiC that looks a panic from failure to decrypt data, I think it should also be fixed on that same branch, please check and let us know?

After MetaMask app upgraded to v7.4.0(1159), both addEthereumChain and switchEthereumChain work well, the error disappeared, and I can't downgrade the app to test your branch.

**Comment by elefantel** [comment] 2023-08-18 13:32
Ok great! The `reconnection-handling` is on this iOS SDK repo not on MetaMask app, but if all good on your side that sounds good. Thanks for the feedback!

**Comment by christopherferreira9** [comment] 2023-09-06 09:58
Hi @nick70007 , following up on this, have you tried with the branch provided by @elefantel ?

**Closed** 2023-09-11 03:56 UTC
